FROM onosproject/onos:2.7-latest

USER root
RUN apt-get update && \
    apt-get install -y curl net-tools iputils-ping

RUN apt-get install -y telnet

ENV JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 $JAVA_TOOL_OPTIONS"

ARG ONOS_DATA_CLASSIFICATION_OAR
ARG ONOS_DATA_CLASSIFICATION_VERSION

#App oar
#COPY onos-app/data-classification/target/$ONOS_DATA_CLASSIFICATION_OAR /root/onos/apps/vn.edu.huce.data-classification/vn.edu.huce.data-classification.oar
#COPY onos-app/data-classification/target/oar/app.xml /root/onos/apps/vn.edu.huce.data-classification/app.xml
#Artifact
#COPY onos-app/data-classification/target/oar/m2/vn/edu/huce/data-classification/$ONOS_DATA_CLASSIFICATION_VERSION/data-classification-$ONOS_DATA_CLASSIFICATION_VERSION-features.xml /root/onos/apache-karaf-4.2.14/system/vn/edu/huce/data-classification/$ONOS_DATA_CLASSIFICATION_VERSION/data-classification-$ONOS_DATA_CLASSIFICATION_VERSION-features.xml

# Lệnh khởi động ONOS khi container chạy
CMD ["onos-service"]

HEALTHCHECK --interval=30s --timeout=10s --retries=3 \
    CMD curl -f http://localhost:8181/onos/ui/login.html || exit 1